### ISSUE TITLE
User can see their car.

### ISSUE THREAD

**Issue by fredrickrana** [fredrickrana/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Find a car image online
- [x] Add the image of the car to the page by setting an image element with the source as an absolute link
- [x] Set a background for the driving game application
- [x] Apply CSS styling to the page and utilize the position property for the car
- [x] Delete all unnecessary CSS/HTML
