### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by fredrickrana** [fredrickrana/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a main.js file 
- [x] Utilize the transform property and create a CSS class for each rotation of the car
- [x] Create a variable for each of the keyCode values of each arrow key [37, 38, 39, 40]
- [x] Change the class name of the race car depending on which arrow key is pressed
- [x] Add an event listener to the window 
- [x] Delete all unnecessary CSS styling
- [x] Test functionality
- [x] Fix all errors
