### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by fredrickrana** [fredrickrana/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Change the race car positioning to absolute
- [x] Create a function with an addEventListener to the window object, that initiates when the space button (key code 32) is pressed
- [x] Utilize setInterval() to continuously change the positioning of the car 
- [x] Clear interval when car reaches the end of the page
- [x] Delete all unnecessary styling
- [x] Test functionality
- [x] Clear all errors
